// [CONTRATO-ESTRUTURAL] wiring de UI do agente (foco, ARIA, SSE, aprovação) acoplado a providers.
// A cobertura comportamental equivalente deve migrar para testes de componente/E2E.
import { describe, expect, test } from 'bun:test'

async function source(path: string) { return fetch(new URL(path, import.meta.url)).then(response => response.text()) }

describe('contratos de interação do Azy Agent', () => {
  test('drawer mantém foco, ARIA, teclado, SSE e decisões retomáveis', async () => {
    const text = await source('./components/AzyAgentDrawer.tsx')
    for (const expected of ['role="dialog"', 'aria-modal="true"', 'aria-live="polite"', "e.key === 'Enter'", 'EventSource', '/assistant/runs/', 'APPROVAL_REQUIRED', 'RUN_FAILED', 'RUN_EXPIRED', 'CLIENT_RUN_TIMEOUT_MS', 'WAITING_USER']) expect(text.includes(expected)).toBe(true)
  })
  test('aprovação usa prévia legível e permite ajustar antes de executar', async () => {
    const text = await source('./components/AzyAgentDrawer.tsx')
    expect(text.includes('previewMarkdown')).toBe(true)
    expect(text.includes('/adjust')).toBe(true)
    expect(text.includes('t("adjust")')).toBe(true)
    expect(text.includes('JSON.stringify(run.approval.preview')).toBe(false)
  })
  test('mutações do agente atualizam a interface sem polling', async () => {
    const drawer = await source('./components/AzyAgentDrawer.tsx')
    const projects = await source('./pages/ProjectsPage.tsx')
    const events = await source('./lib/dataEvents.ts')
    expect(drawer.includes('notifyAssistantMutation')).toBe(true)
    expect(projects.includes('onAssistantMutation')).toBe(true)
    expect(projects.includes("toolName === 'create_project'")).toBe(true)
    expect(projects.includes("toolName === 'create_project_structure'")).toBe(true)
    expect(projects.includes('payload.project ?? payload')).toBe(true)
    expect(events.includes('setInterval')).toBe(false)
  })
  test('mensagens longas são bloqueadas antes de criar uma run', async () => {
    const text = await source('./components/AzyAgentDrawer.tsx')
    expect(text.includes(`import { MAX_MESSAGE_BYTES } from '@azy-board/assistant-contracts'`)).toBe(true)
    expect(text.includes('MAX_MESSAGE_CHARS = MAX_MESSAGE_BYTES')).toBe(true)
    expect(text.includes('messageTooLong')).toBe(true)
    expect(text.includes('maxLength={MAX_MESSAGE_CHARS}')).toBe(true)
    expect(text.includes('ACTION_LIMIT: t("actionLimit")')).toBe(true)
  })
  test('drawer inicia uma sessão nova sem carregar ou exibir histórico', async () => {
    const text = await source('./components/AzyAgentDrawer.tsx')
    expect(text.includes('/assistant/conversations')).toBe(true)
    expect(text.includes('.get<Conversation[]>')).toBe(false)
    expect(text.includes('history')).toBe(false)
    expect(text.includes('function openDrawer')).toBe(true)
    expect(text.includes('conversation.projectId === (projectId ?? null)')).toBe(true)
    expect(text.includes('{ content: text, screen: pageContext?.screen ?? \'global-other\', projectId: projectId ?? null, itemId: itemId ?? null }')).toBe(true)
  })
  test('propaga item selecionado, mostra breadcrumb e reconcilia conclusão por runId', async () => {
    const drawer = await source('./components/AzyAgentDrawer.tsx')
    const context = await source('./contexts/AssistantContext.tsx')
    const shell = await source('./components/AppShell.tsx')
    const board = await source('./features/board/BoardScreen.tsx')
    expect(context.includes('pageContext')).toBe(true)
    expect(context.includes('screen')).toBe(true)
    expect(shell.includes('assistantSelectedItem')).toBe(true)
    expect(shell.includes('inferredScreen')).toBe(true)
    expect(board.includes('storyModalData?.story?.id')).toBe(true)
    expect(board.includes('epicModalData?.epic?.id')).toBe(true)
    expect(drawer.includes('aria-label={t("contextBreadcrumb")}')).toBe(true)
    expect(drawer.includes('reconcileTerminalRun')).toBe(true)
    expect(drawer.includes('message.metadata?.runId === runId')).toBe(true)
    expect(drawer.includes('completedWithoutMessage')).toBe(true)
    expect(drawer.includes('tool.displayName')).toBe(true)
    expect(drawer.includes('tool.toolName}:')).toBe(false)
  })
  test('configuração do tenant fica no submenu de Admin com acesso Root', async () => {
    const text = await source('./components/AppShell.tsx')
    expect(text.includes('children:')).toBe(true)
    expect(text.includes("user.globalGroup === 'ROOT'")).toBe(true)
    expect(text.includes("href: '/admin/assistant'")).toBe(true)
    expect(text.includes("href: '/admin/users'")).toBe(true)
    expect(text.includes('aria-expanded={adminExpanded}')).toBe(true)
  })
  test('configuração Root não envia credenciais para contexto global', async () => {
    const context = await source('./contexts/AssistantContext.tsx')
    const settings = await source('./components/RootAssistantSettings.tsx')
    expect(context.includes('secret')).toBe(false)
    expect(settings.includes('/assistant/root/provider/rotate')).toBe(true)
    expect(settings.includes('OAUTH')).toBe(false)
    expect(settings.includes('oauthUnsupported')).toBe(false)
  })
  test('governança do Root usa a fonte única de limites', async () => {
    const settings = await source('./components/RootAssistantSettings.tsx')
    expect(settings.includes(`import { DEFAULT_GOVERNANCE } from '@azy-board/assistant-contracts'`)).toBe(true)
    expect(settings.includes('useState({ ...DEFAULT_GOVERNANCE })')).toBe(true)
    expect(settings.includes('maxSteps: 4')).toBe(false)
    expect(settings.includes('maxPayloadBytes: 50_000')).toBe(false)
  })
})
