import type { KeyboardEvent, ReactNode } from 'react'
import { Cell, Bar, BarChart, Area, AreaChart, CartesianGrid, Legend, Pie, PieChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import type { ChartDatum } from '../../dashboardAdapters'

export const COLORS = ['var(--dashboard-series-scope)', 'var(--dashboard-series-done)', 'var(--dashboard-series-warning)', 'var(--dashboard-series-danger)', 'var(--dashboard-series-neutral)']
export function MetricValue({ label, value }: { label: string; value: string | number }) { return <div><span className="block text-xs text-muted-foreground">{label}</span><strong className="mt-1 block text-2xl tabular-nums text-foreground">{value}</strong></div> }
export function ChartLegend({ items }: { items: string[] }) { return <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-muted-foreground">{items.map((item, index) => <span key={item}><i className="mr-1 inline-block h-2 w-2 rounded-full" style={{ backgroundColor: COLORS[index % COLORS.length] }} />{item}</span>)}</div> }
export function ChartTooltip({ active, payload, label }: { active?: boolean; payload?: Array<{ name?: string; value?: number | string; color?: string; payload?: { id?: string; title?: string; type?: string; unit?: string } }>; label?: string }) { if (!active || !payload?.length) return null; const source = payload[0]?.payload; return <div className="rounded-lg border border-border bg-surface-raised px-3 py-2 text-xs shadow-lg"><strong>{source?.title ?? label}</strong>{source?.title && <div className="text-muted-foreground">ID: {source.id ?? label}</div>}{source?.type && <div>{source.type}</div>}{payload.map(item => <div key={item.name}><span style={{ color: item.color }}>{item.name}: </span>{item.value}{source?.unit ? ` ${source.unit}` : ''}</div>)}</div> }
export function ChartSkeleton() { return <div className="h-36 animate-pulse rounded-lg bg-muted" role="status" aria-label="Loading chart" /> }
export function ChartEmptyState({ children = 'No data available for this view' }: { children?: ReactNode }) { return <div className="flex h-36 items-center justify-center rounded-lg border border-dashed border-border px-4 text-center text-sm text-muted-foreground" role="status">{children}</div> }
export function DashboardCard({ title, icon: Icon, children, state = 'ready', partial, message, onRetry, description }: { title: string; icon: React.ComponentType<{ className?: string }>; children: ReactNode; state?: string; partial?: boolean; message?: ReactNode; onRetry?: () => void; description: string }) { return <section className="dashboard-box flex min-h-[330px] flex-col rounded-2xl border border-border bg-surface p-5 shadow-sm" aria-labelledby={`dashboard-${title}`}><div className="mb-4 flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="h-5 w-5" /></span><div className="min-w-0"><h2 id={`dashboard-${title}`} className="font-semibold text-foreground">{title}</h2>{partial && <span className="text-[11px] text-amber-700 dark:text-amber-300">Partial coverage</span>}</div></div>{state === 'loading' ? <ChartSkeleton /> : state === 'empty' || state === 'inapplicable' ? <ChartEmptyState>{message ?? (state === 'inapplicable' ? 'This filter does not apply to this view.' : undefined)}</ChartEmptyState> : state === 'error' ? <div className="text-sm text-destructive" role="alert">Unable to load this view. {onRetry && <button className="font-semibold underline" onClick={onRetry}>Retry</button>}</div> : <div className="min-h-0 flex-1">{children}</div>}<p className="mt-4 border-t border-border pt-3 text-xs leading-relaxed text-muted-foreground">{description}</p></section> }
export function Donut({ data, onSliceClick }: { data: ChartDatum[]; onSliceClick?: (index: number) => void }) { return <ResponsiveContainer width="100%" height={150}><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={43} outerRadius={62} paddingAngle={3} isAnimationActive={false}>{data.map((entry, index) => <Cell key={String(entry.name)} fill={COLORS[index]} cursor={onSliceClick ? 'pointer' : undefined} role={onSliceClick ? 'button' : undefined} tabIndex={onSliceClick ? 0 : undefined} className={onSliceClick ? 'focus-visible:outline focus-visible:outline-2 focus-visible:outline-primary' : undefined} aria-label={onSliceClick ? `${entry.name}: ${entry.value}` : undefined} onClick={onSliceClick ? () => onSliceClick(index) : undefined} onKeyDown={onSliceClick ? (event: KeyboardEvent<SVGElement>) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); onSliceClick(index) } } : undefined} />)}</Pie><Tooltip content={<ChartTooltip />} /></PieChart></ResponsiveContainer> }
export function Gauge({ value, total, label, unit = '%' }: { value: number; total: number; label: string; unit?: string }) { const safeTotal = Math.max(total, 0); const percent = safeTotal ? Math.min(100, Math.max(0, value / safeTotal * 100)) : 0; return <div className="relative h-[150px]" role="img" aria-label={`${label}: ${value}/${total}, ${Math.round(percent)}${unit}`}><ResponsiveContainer width="100%" height={150}><PieChart><Pie data={[{ value: percent }, { value: 100 - percent }]} dataKey="value" startAngle={180} endAngle={0} innerRadius={48} outerRadius={66} paddingAngle={1} isAnimationActive={false}><Cell fill={COLORS[1]} /><Cell fill="var(--dashboard-series-neutral)" /></Pie></PieChart></ResponsiveContainer><div className="absolute inset-x-0 bottom-5 text-center"><strong className="block text-xl tabular-nums">{value}/{total}</strong><span className="text-xs text-muted-foreground">{Math.round(percent)}{unit} {label}</span></div></div> }
export function DonutComparison({ title, selected, total, selectedLabel, totalLabel, onSliceClick }: { title: string; selected: number; total: number; selectedLabel: string; totalLabel: string; onSliceClick?: (index: number) => void }) { return <div><Donut data={[{ name: selectedLabel, value: selected }, { name: totalLabel, value: Math.max(0, total - selected) }]} onSliceClick={onSliceClick} /><div className="text-center text-xs text-muted-foreground"><strong className="text-base text-foreground">{selected}/{total}</strong> · {title}</div></div> }
export function HorizontalRankingBar({ data, unit, onSelect }: { data: ChartDatum[]; unit: string; onSelect?: (id: string) => void }) { return <ResponsiveContainer width="100%" height={Math.max(155, data.length * 30)}><BarChart data={data} layout="vertical" margin={{ left: 8, right: 35 }}><CartesianGrid strokeDasharray="3 3" horizontal={false} opacity={0.2} /><XAxis type="number" unit={` ${unit}`} allowDecimals /><YAxis type="category" dataKey="name" width={100} tick={{ fontSize: 11 }} /><Tooltip content={<ChartTooltip />} /><Bar dataKey="value" fill={COLORS[3]} radius={[0, 5, 5, 0]} isAnimationActive={false} onClick={entry => { const id = String((entry as { id?: string }).id ?? ''); if (id) onSelect?.(id) }} /></BarChart></ResponsiveContainer> }
export function SimpleBars({ data, dataKey = 'value', nameKey = 'name' }: { data: ChartDatum[]; dataKey?: string; nameKey?: string }) { return <ResponsiveContainer width="100%" height={155}><BarChart data={data} layout="vertical" margin={{ left: 8, right: 8 }}><CartesianGrid strokeDasharray="3 3" horizontal={false} opacity={0.2} /><XAxis type="number" allowDecimals={false} /><YAxis type="category" dataKey={nameKey} width={82} tick={{ fontSize: 11 }} /><Tooltip content={<ChartTooltip />} /><Bar dataKey={dataKey} fill={COLORS[0]} radius={[0, 5, 5, 0]} isAnimationActive={false} /></BarChart></ResponsiveContainer> }
export function TimeArea({ data, reference }: { data: ChartDatum[]; reference?: string }) { return <ResponsiveContainer width="100%" height={180}><AreaChart data={data} margin={{ left: 0, right: 8 }}><CartesianGrid strokeDasharray="3 3" opacity={0.2} /><XAxis dataKey="date" tick={{ fontSize: 10 }} minTickGap={24} /><YAxis allowDecimals={false} width={28} /><Tooltip content={<ChartTooltip />} /><Legend /><Area type="monotone" dataKey="scope" name="Scope" stroke={COLORS[0]} fill={COLORS[0]} fillOpacity={0.14} isAnimationActive={false} /><Area type="monotone" dataKey="done" name="Done" stroke={COLORS[1]} fill={COLORS[1]} fillOpacity={0.18} isAnimationActive={false} />{reference && <ReferenceLine x={reference} stroke={COLORS[2]} label="Coverage" />}</AreaChart></ResponsiveContainer> }
