/**
 * Teste automatizado de backup e restore do Azy Board.
 *
 * Uso: bun run test:restore [--perfil SIMPLE|ADVANCED] [--compose-file <arquivo>]
 *
 * Orquestra uma instância EFÊMERA (COMPOSE_PROJECT_NAME próprio, volumes
 * destruídos ao final):
 *   1. sobe a instância (job `migrate` antes da API);
 *   2. grava dados-sonda (linha no banco + arquivo em uploads);
 *   3. executa o backup (`deploy-backup`);
 *   4. destrói os volumes (`down -v`);
 *   5. sobe uma instância nova e restaura o backup (`deploy-restore`);
 *   6. verifica que as sondas e o /health/ready voltaram intactos.
 *
 * Qualquer falha encerra com código diferente de zero (gate de CI).
 */
import { carimboDeData, type Perfil } from './deploy-lib'

const args = Bun.argv.slice(2)
function argValue(flag: string): string | undefined {
  const idx = args.indexOf(flag)
  return idx >= 0 ? args[idx + 1] : undefined
}

const perfil = (argValue('--perfil')?.toUpperCase() as Perfil) || 'SIMPLE'
if (perfil !== 'SIMPLE' && perfil !== 'ADVANCED') {
  throw new Error('--perfil deve ser SIMPLE ou ADVANCED.')
}
const composeFile =
  argValue('--compose-file') ||
  process.env.COMPOSE_FILE ||
  (perfil === 'ADVANCED' ? 'docker-compose.advanced.yml' : 'docker-compose.simple.yml')

// Projeto efêmero: isola volumes/nomes sem tocar em instalações reais.
const projectName = `azyboard-test-restore-${carimboDeData().toLowerCase()}`
const env = { ...process.env, COMPOSE_PROJECT_NAME: projectName }
const out = `tmp/test-restore-${projectName}`

function compose(
  args2: string[],
  opts: { capture?: boolean; allowFailure?: boolean; stdinPath?: string } = {},
): ReturnType<typeof Bun.spawnSync> {
  return Bun.spawnSync(['docker', 'compose', '-f', composeFile, ...args2], {
    env,
    stdin: opts.stdinPath ? Bun.file(opts.stdinPath) : 'inherit',
    stdout: opts.capture ? 'pipe' : 'inherit',
    stderr: 'inherit',
  })
}

function oneShot(service: string, entrypoint: string, cmdArgs: string[], opts: { capture?: boolean } = {}): string {
  const r = compose(['run', '--rm', '--no-deps', '--entrypoint', entrypoint, service, ...cmdArgs], opts)
  return opts.capture ? new TextDecoder().decode(r.stdout).trim() : ''
}

function verificar(condicao: boolean, mensagem: string) {
  if (!condicao) throw new Error(`FALHA DO TESTE DE RESTORE: ${mensagem}`)
  console.log(`✓ ${mensagem}`)
}

const SONDASQL =
  perfil === 'SIMPLE'
    ? 'const {Database}=require("bun:sqlite");const db=new Database(process.env.DATABASE_URL);db.exec("CREATE TABLE IF NOT EXISTS restore_probe (id INTEGER PRIMARY KEY, valor TEXT NOT NULL)");db.prepare("INSERT INTO restore_probe (valor) VALUES (?)").run("antes-do-backup");db.close();'
    : 'CREATE TABLE IF NOT EXISTS restore_probe (id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, valor TEXT NOT NULL); INSERT INTO restore_probe (valor) VALUES (\'antes-do-backup\');'

const LERSQL =
  perfil === 'SIMPLE'
    ? 'const {Database}=require("bun:sqlite");const db=new Database(process.env.DATABASE_URL);console.log(db.query("SELECT valor FROM restore_probe ORDER BY id DESC LIMIT 1").get()?.valor ?? "");db.close();'
    : 'SELECT valor FROM restore_probe ORDER BY id DESC LIMIT 1;'

function semear() {
  if (perfil === 'SIMPLE') {
    oneShot('migrate', 'bun', ['-e', SONDASQL])
  } else {
    compose(['exec', '-T', 'postgres', 'sh', '-c', `psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -q -c "${SONDASQL}"`])
  }
  oneShot('migrate', 'sh', ['-c', 'echo antes-do-backup > /app/uploads/restore-probe.txt'])
}

function lerSondaBanco(): string {
  if (perfil === 'SIMPLE') {
    return oneShot('migrate', 'bun', ['-e', LERSQL], { capture: true })
  }
  const r = compose(['exec', '-T', 'postgres', 'sh', '-c', `psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -tA -c "${LERSQL}"`], {
    capture: true,
  })
  return new TextDecoder().decode(r.stdout).trim()
}

function aguardarApi(timeoutSeg = 90) {
  for (let i = 0; i < timeoutSeg; i++) {
    const r = compose(['exec', '-T', 'azyboard', 'wget', '-qO-', 'http://localhost:3000/health/ready'], {
      capture: true,
      allowFailure: true,
    })
    if (r.success) return
    Bun.sleepSync(1000)
  }
  throw new Error(`API não ficou pronta em ${timeoutSeg}s (verifique 'docker compose logs').`)
}

console.log(`=== Teste de restore (${perfil}) — projeto ${projectName} ===`)

try {
  console.log('\n[1/7] Subindo instância efêmera...')
  compose(['down', '-v', '--remove-orphans'], { allowFailure: true })
  compose(['up', '-d'])
  aguardarApi()

  console.log('\n[2/7] Gravando dados-sonda...')
  semear()

  console.log('\n[3/7] Executando backup...')
  const backup = Bun.spawnSync(['bun', 'run', 'scripts/deploy-backup.ts', '--out', out, '--perfil', perfil, '--compose-file', composeFile], {
    env,
    stdout: 'inherit',
    stderr: 'inherit',
  })
  verificar(backup.success, 'backup executado sem erro')

  console.log('\n[4/7] Destruindo volumes (down -v)...')
  compose(['down', '-v', '--remove-orphans'])

  console.log('\n[5/7] Subindo instância nova...')
  compose(['up', '-d'])
  aguardarApi()

  console.log('\n[6/7] Restaurando backup...')
  const restore = Bun.spawnSync(['bun', 'run', 'scripts/deploy-restore.ts', out, '--compose-file', composeFile], {
    env,
    stdout: 'inherit',
    stderr: 'inherit',
  })
  verificar(restore.success, 'restore executado sem erro')
  aguardarApi()

  console.log('\n[7/7] Verificando integridade...')
  const valor = lerSondaBanco()
  verificar(valor.includes('antes-do-backup'), `sonda do banco restaurada (valor: "${valor.trim()}")`)
  const arquivo = oneShot('migrate', 'sh', ['-c', 'cat /app/uploads/restore-probe.txt'], { capture: true })
  verificar(arquivo.includes('antes-do-backup'), 'sonda de uploads restaurada')
  const health = compose(['exec', '-T', 'azyboard', 'wget', '-qO-', 'http://localhost:3000/health/ready'], {
    capture: true,
    allowFailure: true,
  })
  verificar(health.success, '/health/ready respondendo após o restore')

  console.log('\n=== Teste de restore PASSOU ===')
} finally {
  compose(['down', '-v', '--remove-orphans'], { allowFailure: true })
}
