const result = await Bun.$`biome lint .`.nothrow()
const stdout = result.stdout.toString()
const stderr = result.stderr.toString()
if (stdout) process.stdout.write(stdout)
if (stderr) process.stderr.write(stderr)
if (result.exitCode !== 0) process.exit(result.exitCode)
console.log('Lint concluído via Biome')
