import {
  Activity,
  Award,
  Bell,
  BookOpen,
  Bookmark,
  Briefcase,
  Brush,
  Bug,
  Building2,
  Calendar,
  Camera,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  Compass,
  Cpu,
  CreditCard,
  Database,
  FileText,
  Film,
  Flag,
  Flame,
  Folder,
  FolderKanban,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  Heart,
  Home,
  Image as ImageIcon,
  Key,
  LayoutDashboard,
  Lightbulb,
  Lock,
  Mail,
  Map as MapIcon,
  Medal,
  MessageSquare,
  Monitor,
  Music,
  Palette,
  PenTool,
  Rocket,
  Server,
  Settings,
  Shield,
  ShoppingCart,
  Smartphone,
  Star,
  Target,
  Terminal,
  Trophy,
  User,
  Users,
  Wallet,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'
import { DEFAULT_ITEM_ICON, DEFAULT_PROJECT_ICON, type IconName } from '@azy-board/ui-contracts'

// Mapa nome do catálogo -> componente lucide. O tipo Record<IconName, LucideIcon>
// garante em tempo de compilação que todo item do ICON_CATALOG tem componente.
export const ICON_COMPONENTS: Record<IconName, LucideIcon> = {
  folder: Folder,
  'folder-kanban': FolderKanban,
  'layout-dashboard': LayoutDashboard,
  rocket: Rocket,
  target: Target,
  flag: Flag,
  star: Star,
  bookmark: Bookmark,
  heart: Heart,
  zap: Zap,
  flame: Flame,
  lightbulb: Lightbulb,
  bug: Bug,
  wrench: Wrench,
  hammer: Hammer,
  settings: Settings,
  shield: Shield,
  lock: Lock,
  key: Key,
  globe: Globe,
  map: MapIcon,
  compass: Compass,
  palette: Palette,
  brush: Brush,
  'pen-tool': PenTool,
  code: Code,
  terminal: Terminal,
  database: Database,
  server: Server,
  cloud: Cloud,
  cpu: Cpu,
  smartphone: Smartphone,
  monitor: Monitor,
  camera: Camera,
  image: ImageIcon,
  film: Film,
  music: Music,
  'gamepad-2': Gamepad2,
  trophy: Trophy,
  medal: Medal,
  award: Award,
  gift: Gift,
  'shopping-cart': ShoppingCart,
  'credit-card': CreditCard,
  wallet: Wallet,
  briefcase: Briefcase,
  'building-2': Building2,
  home: Home,
  users: Users,
  user: User,
  calendar: Calendar,
  clock: Clock,
  bell: Bell,
  mail: Mail,
  'message-square': MessageSquare,
  'file-text': FileText,
  'clipboard-list': ClipboardList,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  activity: Activity,
}

export function iconComponent(name: string | null | undefined): LucideIcon | null {
  if (!name) return null
  return (ICON_COMPONENTS as Record<string, LucideIcon>)[name] ?? null
}

export function projectIconComponent(name: string | null | undefined): LucideIcon {
  return iconComponent(name) ?? ICON_COMPONENTS[DEFAULT_PROJECT_ICON]
}

export function itemIconComponent(name: string | null | undefined): LucideIcon {
  return iconComponent(name) ?? ICON_COMPONENTS[DEFAULT_ITEM_ICON]
}
