import {
  Activity,
  AlarmClock,
  Antenna,
  Archive,
  ArchiveRestore,
  ArrowUpDown,
  Atom,
  Award,
  Badge,
  BadgeCheck,
  Bell,
  BellRing,
  Binary,
  Blocks,
  Book,
  Bookmark,
  BookMarked,
  BookOpen,
  Bot,
  Box,
  Boxes,
  Braces,
  Brain,
  BrainCircuit,
  Briefcase,
  Brush,
  Bug,
  Building,
  Building2,
  Cable,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarRange,
  Camera,
  ChartColumn,
  ChartGantt,
  ChartLine,
  ChartNoAxesCombined,
  ChartPie,
  CircleHelp,
  CircuitBoard,
  ClipboardCheck,
  ClipboardList,
  ClipboardX,
  Clock,
  Cloud,
  Code,
  Columns,
  Compass,
  Construction,
  Contact,
  Container,
  Cpu,
  CreditCard,
  Crosshair,
  Crown,
  Database,
  DatabaseBackup,
  DatabaseZap,
  Diamond,
  Dna,
  Factory,
  File,
  FileCheck,
  FileClock,
  Files,
  FileText,
  FileWarning,
  FileX,
  Film,
  Fingerprint,
  Flag,
  FlagTriangleRight,
  Flame,
  FlaskConical,
  Folder,
  FolderClock,
  FolderGit,
  FolderKanban,
  FolderPlus,
  Folders,
  FolderSearch,
  FolderTree,
  GalleryHorizontal,
  GalleryVertical,
  Gamepad2,
  Gauge,
  Gem,
  Gift,
  GitBranch,
  GitCommit,
  Github,
  Gitlab,
  GitMerge,
  GitPullRequest,
  Globe,
  Goal,
  GraduationCap,
  HardDrive,
  HardHat,
  Headphones,
  Headset,
  Heart,
  HeartPulse,
  Highlighter,
  History,
  Home,
  Hourglass,
  IdCard,
  Image as ImageIcon,
  Inbox,
  Joystick,
  Kanban,
  KanbanSquare,
  Key,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LifeBuoy,
  Lightbulb,
  ListChecks,
  ListFilter,
  ListTodo,
  ListTree,
  Lock,
  Mail,
  MailCheck,
  Map as MapIcon,
  Medal,
  MemoryStick,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Milestone,
  Monitor,
  Music,
  Network,
  NotebookPen,
  OctagonAlert,
  Orbit,
  Package,
  Palette,
  Pen,
  Pencil,
  PenTool,
  Phone,
  PhoneCall,
  PhoneIncoming,
  PhoneMissed,
  PhoneOutgoing,
  Plug,
  Presentation,
  QrCode,
  Radar,
  Radio,
  Recycle,
  RefreshCw,
  Repeat,
  Rocket,
  RotateCw,
  Route,
  Router,
  Satellite,
  Scaling,
  Scan,
  ScanFace,
  Send,
  Server,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Signal,
  Signpost,
  SignpostBig,
  Siren,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Star,
  Stethoscope,
  Store,
  Table,
  Table2,
  Target,
  Terminal,
  TestTube,
  TestTubeDiagonal,
  TestTubes,
  Ticket,
  TicketCheck,
  Timer,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Truck,
  Tv,
  User,
  UserCog,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  Wallet,
  Wand,
  WandSparkles,
  Warehouse,
  Watch,
  Waypoints,
  Webhook,
  Wifi,
  Workflow,
  Zap,
  type LucideIcon,
} from 'lucide-react'
import { DEFAULT_ITEM_ICON, DEFAULT_PROJECT_ICON, type IconName } from '@azy-board/ui-contracts'

// Mapa nome do catálogo -> componente lucide. O tipo Record<IconName, LucideIcon>
// garante em tempo de compilação que todo item do ICON_CATALOG tem componente.
export const ICON_COMPONENTS: Record<IconName, LucideIcon> = {
  "code": Code,
  "terminal": Terminal,
  "git-branch": GitBranch,
  "git-merge": GitMerge,
  "git-pull-request": GitPullRequest,
  "git-commit": GitCommit,
  "github": Github,
  "gitlab": Gitlab,
  "container": Container,
  "box": Box,
  "boxes": Boxes,
  "package": Package,
  "webhook": Webhook,
  "network": Network,
  "wifi": Wifi,
  "router": Router,
  "hard-drive": HardDrive,
  "memory-stick": MemoryStick,
  "circuit-board": CircuitBoard,
  "cpu": Cpu,
  "smartphone": Smartphone,
  "monitor": Monitor,
  "plug": Plug,
  "cable": Cable,
  "qr-code": QrCode,
  "binary": Binary,
  "braces": Braces,
  "blocks": Blocks,
  "workflow": Workflow,
  "waypoints": Waypoints,
  "bot": Bot,
  "bug": Bug,
  "zap": Zap,
  "lightbulb": Lightbulb,
  "settings": Settings,
  "server": Server,
  "cloud": Cloud,
  "ticket": Ticket,
  "ticket-check": TicketCheck,
  "clipboard-check": ClipboardCheck,
  "clipboard-x": ClipboardX,
  "list-checks": ListChecks,
  "refresh-cw": RefreshCw,
  "rotate-cw": RotateCw,
  "repeat": Repeat,
  "recycle": Recycle,
  "life-buoy": LifeBuoy,
  "heart-pulse": HeartPulse,
  "stethoscope": Stethoscope,
  "siren": Siren,
  "triangle-alert": TriangleAlert,
  "octagon-alert": OctagonAlert,
  "shield-check": ShieldCheck,
  "shield-alert": ShieldAlert,
  "shield": Shield,
  "lock": Lock,
  "key": Key,
  "headset": Headset,
  "phone-call": PhoneCall,
  "history": History,
  "gauge": Gauge,
  "timer": Timer,
  "hourglass": Hourglass,
  "circle-help": CircleHelp,
  "file-warning": FileWarning,
  "bell-ring": BellRing,
  "activity": Activity,
  "folder-kanban": FolderKanban,
  "kanban": Kanban,
  "kanban-square": KanbanSquare,
  "layout-dashboard": LayoutDashboard,
  "columns": Columns,
  "layout-grid": LayoutGrid,
  "list-todo": ListTodo,
  "list-tree": ListTree,
  "table": Table,
  "chart-column": ChartColumn,
  "chart-line": ChartLine,
  "chart-pie": ChartPie,
  "chart-gantt": ChartGantt,
  "chart-no-axes-combined": ChartNoAxesCombined,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "milestone": Milestone,
  "flag-triangle-right": FlagTriangleRight,
  "goal": Goal,
  "crosshair": Crosshair,
  "route": Route,
  "signpost": Signpost,
  "signpost-big": SignpostBig,
  "scaling": Scaling,
  "layers": Layers,
  "archive": Archive,
  "archive-restore": ArchiveRestore,
  "inbox": Inbox,
  "folders": Folders,
  "folder-tree": FolderTree,
  "folder-git": FolderGit,
  "folder-clock": FolderClock,
  "calendar-check": CalendarCheck,
  "calendar-range": CalendarRange,
  "calendar-clock": CalendarClock,
  "rocket": Rocket,
  "target": Target,
  "flag": Flag,
  "flame": Flame,
  "users": Users,
  "user": User,
  "users-round": UsersRound,
  "user-round": UserRound,
  "user-cog": UserCog,
  "user-plus": UserPlus,
  "home": Home,
  "building": Building,
  "building-2": Building2,
  "landmark": Landmark,
  "factory": Factory,
  "warehouse": Warehouse,
  "construction": Construction,
  "hard-hat": HardHat,
  "truck": Truck,
  "briefcase": Briefcase,
  "id-card": IdCard,
  "badge-check": BadgeCheck,
  "contact": Contact,
  "heart": Heart,
  "star": Star,
  "bookmark": Bookmark,
  "globe": Globe,
  "map": MapIcon,
  "compass": Compass,
  "folder": Folder,
  "file-text": FileText,
  "clipboard-list": ClipboardList,
  "book-open": BookOpen,
  "book-marked": BookMarked,
  "book": Book,
  "file": File,
  "files": Files,
  "file-check": FileCheck,
  "file-x": FileX,
  "file-clock": FileClock,
  "palette": Palette,
  "brush": Brush,
  "pen-tool": PenTool,
  "pen": Pen,
  "pencil": Pencil,
  "highlighter": Highlighter,
  "folder-plus": FolderPlus,
  "folder-search": FolderSearch,
  "notebook-pen": NotebookPen,
  "graduation-cap": GraduationCap,
  "trophy": Trophy,
  "medal": Medal,
  "award": Award,
  "gem": Gem,
  "crown": Crown,
  "diamond": Diamond,
  "store": Store,
  "badge": Badge,
  "gift": Gift,
  "shopping-cart": ShoppingCart,
  "credit-card": CreditCard,
  "wallet": Wallet,
  "calendar": Calendar,
  "clock": Clock,
  "bell": Bell,
  "alarm-clock": AlarmClock,
  "watch": Watch,
  "mail": Mail,
  "mail-check": MailCheck,
  "send": Send,
  "message-square": MessageSquare,
  "messages-square": MessagesSquare,
  "message-circle": MessageCircle,
  "phone": Phone,
  "phone-incoming": PhoneIncoming,
  "phone-outgoing": PhoneOutgoing,
  "phone-missed": PhoneMissed,
  "database": Database,
  "database-zap": DatabaseZap,
  "database-backup": DatabaseBackup,
  "brain-circuit": BrainCircuit,
  "brain": Brain,
  "sparkles": Sparkles,
  "atom": Atom,
  "orbit": Orbit,
  "dna": Dna,
  "flask-conical": FlaskConical,
  "test-tube": TestTube,
  "test-tube-diagonal": TestTubeDiagonal,
  "test-tubes": TestTubes,
  "wand-sparkles": WandSparkles,
  "wand": Wand,
  "scan-face": ScanFace,
  "fingerprint": Fingerprint,
  "table-2": Table2,
  "list-filter": ListFilter,
  "sliders-horizontal": SlidersHorizontal,
  "arrow-up-down": ArrowUpDown,
  "scan": Scan,
  "radar": Radar,
  "signal": Signal,
  "camera": Camera,
  "image": ImageIcon,
  "film": Film,
  "music": Music,
  "gamepad-2": Gamepad2,
  "tv": Tv,
  "presentation": Presentation,
  "headphones": Headphones,
  "gallery-horizontal": GalleryHorizontal,
  "gallery-vertical": GalleryVertical,
  "joystick": Joystick,
  "radio": Radio,
  "satellite": Satellite,
  "antenna": Antenna,
}

export function iconComponent(name: string | null | undefined): LucideIcon | null {
  if (!name) return null
  return (ICON_COMPONENTS as Record<string, LucideIcon>)[name] ?? null
}

export function projectIconComponent(name: string | null | undefined): LucideIcon {
  return iconComponent(name) ?? ICON_COMPONENTS[DEFAULT_PROJECT_ICON]
}

export function itemIconComponent(name: string | null | undefined): LucideIcon {
  return iconComponent(name) ?? ICON_COMPONENTS[DEFAULT_ITEM_ICON]
}
