import { useState, type FormEvent } from 'react'
import { Check, Network, Pencil, Trash2, UserPlus, Users, X } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { AccordionSection } from '../../../components/AccordionSection'
import type { Column, CostCenter, Manager, Member, Squad } from '../model/types'
import type { ColumnBaseStatus } from '@azy-board/domain'

interface Props {
  projectId?: string
  columns: Column[]; members: Member[]; squads: Squad[]; costCenters: CostCenter[]; manager: Manager | null
  isAdmin: boolean; currentUserId?: string
  openSections: Set<string>; onToggleSection: (id: string) => void
  onCreateColumn: (name: string, status: ColumnBaseStatus) => Promise<void>; onRenameColumn: (id: string, name: string) => Promise<void>
  onDeleteColumn: (column: Column, moveToColumnId: string) => Promise<void>
  onCreateSquad: (name: string) => Promise<void>; onRenameSquad: (id: string, name: string) => Promise<void>; onDeleteSquad: (squad: Squad) => Promise<void>
  onAddMember: (data: { email: string; role: string; squadId: string }) => Promise<void>; onEditMember: (member: Member, role: string, squadId: string) => Promise<void>; onRemoveMember: (member: Member) => Promise<void>
  onCreateCostCenter: (code: string, description: string) => Promise<void>; onEditCostCenter: (id: string, code: string, description: string) => Promise<void>; onDeleteCostCenter: (id: string) => Promise<void>
}

const statuses: ColumnBaseStatus[] = ['NOT_STARTED', 'IN_PROGRESS', 'BLOCKED', 'DONE', 'CANCELLED']
const roleLabel = (role: string, t: (key: string) => string) => role === 'ADMIN' ? 'Admin' : role === 'MEMBER' ? t('settings:roleMember') : role === 'VIEWER' ? t('settings:roleViewer') : role

export function OrganizationSettingsSections(props: Props) {
  const { t } = useTranslation(['settings', 'common'])
  const [columnName, setColumnName] = useState(''); const [columnStatus, setColumnStatus] = useState<ColumnBaseStatus>('NOT_STARTED'); const [editingColumn, setEditingColumn] = useState<Column | null>(null); const [deleteColumn, setDeleteColumn] = useState<Column | null>(null); const [moveTo, setMoveTo] = useState('')
  const [squadName, setSquadName] = useState(''); const [editingSquad, setEditingSquad] = useState<Squad | null>(null); const [deleteSquad, setDeleteSquad] = useState<Squad | null>(null)
  const [memberDialog, setMemberDialog] = useState<'add' | 'edit' | null>(null); const [member, setMember] = useState<Member | null>(null); const [memberForm, setMemberForm] = useState({ email: '', role: 'MEMBER', squadId: '' }); const [removeMember, setRemoveMember] = useState<Member | null>(null); const [structure, setStructure] = useState(false)
  const [ccCode, setCcCode] = useState(''); const [ccDescription, setCcDescription] = useState(''); const [editingCc, setEditingCc] = useState<CostCenter | null>(null)
  const section = (id: string) => ({ isOpen: props.openSections.has(id), onToggle: props.onToggleSection })
  const submit = (callback: () => Promise<void>) => (event: FormEvent) => { event.preventDefault(); void callback() }

  return <>
    <AccordionSection id="columns" title={t('settings:columns')} {...section('columns')}>
      <div className="space-y-2">{props.columns.map(column => <div key={column.id} className="flex items-center justify-between bg-card border border-border rounded-lg px-4 py-3">{editingColumn?.id === column.id ? <div className="flex gap-2 flex-1 mr-2"><input autoFocus value={editingColumn.name} onChange={e => setEditingColumn({ ...editingColumn, name: e.target.value })} className="flex-1 text-sm px-2 py-1 border border-border rounded-lg bg-background" /><button onClick={() => { void props.onRenameColumn(column.id, editingColumn.name); setEditingColumn(null) }}><Check className="w-4 h-4" /></button><button onClick={() => setEditingColumn(null)}><X className="w-4 h-4" /></button></div> : <span className="font-medium text-foreground text-sm">{column.name}</span>}<div className="flex items-center gap-2"><span className="text-xs text-muted-foreground bg-muted px-2 py-1 rounded">{t(`common:status.${column.baseStatus}`)}</span>{props.isAdmin && editingColumn?.id !== column.id && <><button onClick={() => setEditingColumn(column)}><Pencil className="w-3.5 h-3.5" /></button><button onClick={() => { setDeleteColumn(column); setMoveTo(props.columns.find(item => item.id !== column.id)?.id ?? '') }}><Trash2 className="w-3.5 h-3.5 text-destructive" /></button></>}</div></div>)}</div>
      {props.isAdmin && <form onSubmit={submit(async () => { await props.onCreateColumn(columnName, columnStatus); setColumnName('') })} className="mt-4 flex gap-3"><input required placeholder={t('settings:columnName')} value={columnName} onChange={e => setColumnName(e.target.value)} className="flex-1 rounded-lg border border-input bg-background px-3 py-2 text-sm" /><select value={columnStatus} onChange={e => setColumnStatus(e.target.value as ColumnBaseStatus)} className="rounded-lg border border-input bg-background px-3 py-2 text-sm">{statuses.map(status => <option key={status} value={status}>{t(`common:status.${status}`)}</option>)}</select><button className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">{t('settings:newColumn')}</button></form>}
    </AccordionSection>

    <AccordionSection id="members-squads" title={t('settings:membersAndSquads')} {...section('members-squads')}>
      <div className="flex items-center justify-between mb-4"><h2 className="text-lg font-semibold text-foreground">{t('settings:membersAndSquads')}</h2><button onClick={() => setStructure(true)} className="flex items-center gap-1.5 text-sm text-primary"><Network className="w-4 h-4" />Ver estrutura</button></div>
      <div className="mb-6"><div className="flex items-center gap-2 mb-3"><Users className="w-4 h-4 text-muted-foreground" /><h3 className="text-sm font-semibold text-foreground">{t('settings:squads')}</h3></div><div className="space-y-2">{props.squads.map(squad => <div key={squad.id} className="flex items-center justify-between bg-card border border-border rounded-lg px-4 py-2.5">{editingSquad?.id === squad.id ? <div className="flex gap-2 flex-1"><input autoFocus value={editingSquad.name} onChange={e => setEditingSquad({ ...editingSquad, name: e.target.value })} className="flex-1 text-sm px-2 py-1 border border-border rounded-lg bg-background" /><button onClick={() => { void props.onRenameSquad(squad.id, editingSquad.name); setEditingSquad(null) }}><Check className="w-4 h-4" /></button><button onClick={() => setEditingSquad(null)}><X className="w-4 h-4" /></button></div> : <span className="text-sm font-medium text-foreground">{squad.name} <span className="text-xs text-muted-foreground">({squad.memberCount} membro{squad.memberCount !== 1 ? 's' : ''})</span></span>}{props.isAdmin && editingSquad?.id !== squad.id && <div className="flex gap-1"><button onClick={() => setEditingSquad(squad)}><Pencil className="w-3.5 h-3.5" /></button><button onClick={() => setDeleteSquad(squad)}><Trash2 className="w-3.5 h-3.5 text-destructive" /></button></div>}</div>)}{props.squads.length === 0 && <p className="text-sm text-muted-foreground italic">{t('settings:noSquads')}</p>}</div>{props.isAdmin && <form onSubmit={submit(async () => { await props.onCreateSquad(squadName); setSquadName('') })} className="mt-3 flex gap-3"><input placeholder={t('settings:squadNamePlaceholder')} value={squadName} onChange={e => setSquadName(e.target.value)} className="flex-1 rounded-lg border border-input bg-background px-3 py-2 text-sm" /><button className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">{t('settings:createSquad')}</button></form>}</div>
      <div><div className="flex items-center justify-between mb-3"><h3 className="text-sm font-semibold text-foreground">{t('settings:projectMembers')}</h3>{props.isAdmin && <button onClick={() => { setMemberDialog('add'); setMemberForm({ email: '', role: 'MEMBER', squadId: '' }) }} className="flex items-center gap-1.5 text-sm text-primary"><UserPlus className="w-4 h-4" />{t('settings:addMember')}</button>}</div><div className="space-y-1.5">{props.members.map(item => <div key={item.userId} className="flex items-center justify-between bg-card border border-border rounded-lg px-4 py-2.5"><div className="min-w-0"><p className="text-sm font-medium text-foreground truncate">{item.name}</p><p className="text-xs text-muted-foreground truncate">{item.email}</p></div><div className="flex items-center gap-2">{item.squadName && <span className="text-xs px-2 py-0.5 rounded-full bg-amber-100 text-amber-700">{item.squadName}</span>}<span className="text-xs px-2 py-0.5 rounded-full bg-muted">{roleLabel(item.role, t)}</span>{props.isAdmin && <><button onClick={() => { setMember(item); setMemberForm({ email: item.email, role: item.role, squadId: item.squadId ?? '' }); setMemberDialog('edit') }}><Pencil className="w-3.5 h-3.5" /></button><button disabled={item.userId === props.currentUserId} onClick={() => setRemoveMember(item)}><Trash2 className="w-3.5 h-3.5 text-destructive" /></button></>}</div></div>)}{props.members.length === 0 && <p className="text-sm text-muted-foreground italic">{t('settings:noMembers')}</p>}</div></div>
    </AccordionSection>

    <AccordionSection id="cost-centers" title={t('settings:costCenters')} {...section('cost-centers')}>
      <div className="space-y-2">{props.costCenters.map(center => <div key={center.id} className="flex items-center justify-between bg-card border border-border rounded-lg px-4 py-3">{editingCc?.id === center.id ? <div className="flex gap-2 flex-1"><input value={editingCc.code} onChange={e => setEditingCc({ ...editingCc, code: e.target.value })} className="w-28 text-sm px-2 py-1 border border-border rounded-lg bg-background" /><input value={editingCc.description ?? ''} onChange={e => setEditingCc({ ...editingCc, description: e.target.value })} className="flex-1 text-sm px-2 py-1 border border-border rounded-lg bg-background" /><button onClick={() => { void props.onEditCostCenter(center.id, editingCc.code, editingCc.description ?? ''); setEditingCc(null) }}><Check className="w-4 h-4" /></button><button onClick={() => setEditingCc(null)}><X className="w-4 h-4" /></button></div> : <div><span className="text-sm font-medium font-mono">{center.code}</span>{center.description && <span className="text-sm text-muted-foreground ml-3">{center.description}</span>}</div>}{props.isAdmin && editingCc?.id !== center.id && <div className="flex gap-1"><button onClick={() => setEditingCc(center)}><Pencil className="w-3.5 h-3.5" /></button><button onClick={() => void props.onDeleteCostCenter(center.id)}><Trash2 className="w-3.5 h-3.5 text-destructive" /></button></div>}</div>)}</div>
      {props.isAdmin && <form onSubmit={submit(async () => { await props.onCreateCostCenter(ccCode, ccDescription); setCcCode(''); setCcDescription('') })} className="mt-4 flex gap-3"><input required placeholder={t('settings:costCenterCodePlaceholder')} value={ccCode} onChange={e => setCcCode(e.target.value)} className="w-40 rounded-lg border border-input bg-background px-3 py-2 text-sm font-mono" /><input placeholder={t('settings:costCenterDescriptionPlaceholder')} value={ccDescription} onChange={e => setCcDescription(e.target.value)} className="flex-1 rounded-lg border border-input bg-background px-3 py-2 text-sm" /><button className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">{t('settings:add')}</button></form>}
    </AccordionSection>

    {deleteColumn && <Confirm title={t('settings:deleteColumnTitle', { name: deleteColumn.name })} onCancel={() => setDeleteColumn(null)} onConfirm={() => { void props.onDeleteColumn(deleteColumn, moveTo); setDeleteColumn(null) }}>{props.columns.length > 1 && <select value={moveTo} onChange={e => setMoveTo(e.target.value)}>{props.columns.filter(item => item.id !== deleteColumn.id).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select>}</Confirm>}
    {deleteSquad && <Confirm title={t('settings:deleteSquadTitle', { name: deleteSquad.name })} onCancel={() => setDeleteSquad(null)} onConfirm={() => { void props.onDeleteSquad(deleteSquad); setDeleteSquad(null) }}>{deleteSquad.memberCount > 0 && <p className="text-sm text-muted-foreground mb-4">{t('settings:squadMembersRemoved', { count: deleteSquad.memberCount })}</p>}</Confirm>}
    {removeMember && <Confirm title={t('settings:removeMemberTitle')} onCancel={() => setRemoveMember(null)} onConfirm={() => { void props.onRemoveMember(removeMember); setRemoveMember(null) }}><p className="text-sm text-muted-foreground mb-4">{t('settings:removeMemberDescription', { name: removeMember.name })}</p></Confirm>}
    {memberDialog && <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="absolute inset-0 bg-black/50" onClick={() => setMemberDialog(null)} /><form onSubmit={submit(async () => { if (memberDialog === 'add') await props.onAddMember(memberForm); else if (member) await props.onEditMember(member, memberForm.role, memberForm.squadId); setMemberDialog(null) })} className="relative bg-card border border-border rounded-xl shadow-2xl w-full max-w-sm p-6 space-y-3"><h3 className="font-semibold text-foreground">{t(memberDialog === 'add' ? 'settings:addMemberTitle' : 'settings:editMemberTitle')}</h3>{memberDialog === 'add' && <input type="email" required placeholder="usuario@empresa.com" value={memberForm.email} onChange={e => setMemberForm({ ...memberForm, email: e.target.value })} className="w-full rounded-lg border border-input bg-background px-3 py-2 text-sm" />}<select value={memberForm.role} onChange={e => setMemberForm({ ...memberForm, role: e.target.value })} className="w-full rounded-lg border border-input bg-background px-3 py-2 text-sm"><option value="ADMIN">Admin</option><option value="MEMBER">{t('settings:roleMember')}</option><option value="VIEWER">{t('settings:roleViewer')}</option></select>{props.squads.length > 0 && <select value={memberForm.squadId} onChange={e => setMemberForm({ ...memberForm, squadId: e.target.value })} className="w-full rounded-lg border border-input bg-background px-3 py-2 text-sm"><option value="">— {t('settings:none')} —</option>{props.squads.map(squad => <option key={squad.id} value={squad.id}>{squad.name}</option>)}</select>}<div className="flex justify-end gap-2"><button type="button" onClick={() => setMemberDialog(null)}>{t('common:cancel')}</button><button className="bg-primary text-primary-foreground px-4 py-1.5 rounded-lg">{t('common:confirm')}</button></div></form></div>}
    {structure && <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="absolute inset-0 bg-black/50" onClick={() => setStructure(false)} /><div className="relative bg-card border border-border rounded-xl shadow-2xl w-full max-w-lg p-6"><div className="flex justify-between mb-5"><h3 className="font-semibold"><Network className="inline w-4 h-4 mr-2" />{t('settings:projectStructure')}</h3><button onClick={() => setStructure(false)}><X className="w-4 h-4" /></button></div><p className="text-sm font-semibold mb-3">{props.manager?.name ?? t('settings:noManagerDefined')}</p>{props.squads.map(squad => <div key={squad.id} className="mb-3 pl-4 border-l-2"><p className="text-sm font-semibold">{squad.name}</p>{props.members.filter(item => item.squadId === squad.id).map(item => <p key={item.userId} className="text-xs py-1">{item.name} <span className="text-muted-foreground">({roleLabel(item.role, t)})</span></p>)}</div>)}</div></div>}
  </>
}

function Confirm({ title, children, onCancel, onConfirm }: { title: string; children?: React.ReactNode; onCancel: () => void; onConfirm: () => void }) {
  const { t } = useTranslation(['settings', 'common'])
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="absolute inset-0 bg-black/50" onClick={onCancel} /><div className="relative bg-card border border-border rounded-xl shadow-2xl w-full max-w-sm p-6"><h3 className="font-semibold text-foreground mb-2">{title}</h3>{children}<div className="flex gap-2 justify-end"><button onClick={onCancel} className="px-3 py-1.5 text-sm bg-muted rounded-lg">{t('common:cancel')}</button><button onClick={onConfirm} className="px-4 py-1.5 text-sm bg-destructive text-destructive-foreground rounded-lg">{t('common:confirm')}</button></div></div></div>
}
